### ISSUE TITLE
error on task protect my.cnf

### ISSUE THREAD

**Issue by ahrib** [dev-sec/ansible-mysql-hardening#20]
Having the below error come up, any thoughts? 

TASK [dev-sec.mysql-hardening : protect my.cnf] ********************************
fatal: [test.app]: FAILED! => {"changed": false, "failed": true, "msg": "src and dest are required for creating links"}

Ansible 2.1.2.0
ansible-mysql-hardening 1.0.0
Ubuntu 16.04.1 LTS

andrej@vagrant:~$ ls -lah /etc/mysql/my.cnf
lrwxrwxrwx 1 root root 24 Oct  8 04:42 /etc/mysql/my.cnf -> /etc/alternatives/my.cnf

update:
In my case adding "follow=yes" to tasks/configure.yml solved my problem

```
    - name: protect my.cnf
      file: path='{{mysql_hardening_mysql_conf}}' mode=0600 owner=root group=root follow=yes
```

**Comment by rndmh3ro** [comment]
Thanks for reporting, will be fixed here:
https://github.com/dev-sec/ansible-mysql-hardening/pull/21
