### ISSUE TITLE
Template fails to render with Python 3

### ISSUE THREAD

**Issue by quulah** [dev-sec/ansible-mysql-hardening#32]
**Describe the bug**
On systems with Python 3 being used, like Ubuntu 18.04, the template fails to render due to usage of `.itermitems()`.

https://github.com/dev-sec/ansible-mysql-hardening/blob/2.0.0/templates/hardening.cnf.j2#L9

**Expected behavior**
No errors.

**Actual behavior**
```paste below
fatal: [mysqltest]: FAILED! => {"changed": false, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

**OS / Environment**
* Python 3, as the Ansible interpreter.

**Role Version**
* 2.0.0

**Comment by quulah** [comment]
There's no `.iteritems()` for dict any more.

https://www.python.org/dev/peps/pep-0469/

**Comment by rndmh3ro** [comment]
Hey @quulah, thanks for that! I'll try to find a fix. 

However note that Python 2.7 is the default for Ubuntu 18.04, see: https://packages.ubuntu.com/bionic/python

**Comment by rndmh3ro** [comment]
Okay, the fix is rather easy, just replace `iteritems` with `items`. Do you mind testing it?
https://github.com/dev-sec/ansible-mysql-hardening/pull/33

**Comment by quulah** [comment]
Actually, Python 3 is the default, but Python 2 is still available. It won't be in the next LTS.

https://wiki.ubuntu.com/BionicBeaver/ReleaseNotes
> Python 2 is no longer installed by default. Python 3 has been updated to 3.6. This is the last LTS release to include Python 2 in main.

The fix itself seems to work.
