### ISSUE TITLE
permissions on /etc/mysql/mysql.cnf too restrictive

### ISSUE THREAD

**Issue by whysthatso** [dev-sec/ansible-mysql-hardening#35]
**Describe the bug**
Mysqld process is run by user mysql.
Upon start it should be able to read config file `mysql.cnf`.
Hardening sets user/group to root:root and mode to 0400.
When starting the daemon it silently ignores the config file. 
Setting permissions to 0444 fixes this.

**Expected behavior**
Config file should be readable by mysql user running the process.

**OS / Environment**
Ubuntu 18.04
Percona mysql server Ver 8.0.15-6 for debian-linux-gnu on x86_64 (Percona Server (GPL), Release '6', Revision '63abd08')

**Ansible Version**

```paste below
ansible 2.8.2
  config file = /home/user/projects/1/ansible.cfg
  configured module search path = ['/home/user/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.7.3 (default, Jun 24 2019, 04:54:02) [GCC 9.1.0]
```

**Role Version**
latest

**Additional context**

As mentioned, this is a Percona setup. There is a bit of linking going on
```
my.cnf -> /etc/mysql/mysql.cnf
```
I am not sure if this is distribution-specific or percona-specific, and how the default mysql 5.7 of ubuntu 18.04 is behaving. 
Maybe i am also misunderstanding how the process gets started, but it is systemd-managed, and i think the root privileges are dropped before the config files are read.

**Comment by rndmh3ro** [comment]
Hey @whysthatso,

 I'm a bit behind on mysql-related things but normally the root-user starts mysql and forks the process to be run by the mysqld user. Is this different with percona?
We should probably add some more testing here.

**Comment by whysthatso** [comment]
yes, that tripped me up as well. it does so, but maybe the config gets read after privilege drop? i am also not sure, however the mode change helped. one could further debug it possibly by setting even more fine grained permissions or even use acl. or maybe with a bit more understanding of mysql could chime in about when/how config gets read. i know too little to be of help here, methinks.

**Comment by rndmh3ro** [comment]
Well it took some time but I can probably reproduce the problem.
The reason is the following:
```
When MariaDB is started with the systemd unit file, it directly starts the mysqld process as the mysql user. Unlike with sysVinit, the mysqld process is not started with mysqld_safe. As a consequence, options will not be read from the [mysqld_safe] option group from option files.
```
source: https://mariadb.com/kb/en/systemd/

A secure deployment according to mysql does this:

```
shell> cd /etc
shell> touch my.cnf
shell> chown root:root my.cnf  
shell> chmod 644 my.cnf
```
source: https://dev.mysql.com/doc/mysql-secure-deployment-guide/8.0/en/secure-deployment-post-install.html#secure-deployment-startup-options


So we do have something to do here. I don't know if we should go the way the linked PR takes or change the ownership of the files to user `mysql`. I'll have to check.
