### ISSUE TITLE
Add Centos 8 support for ansible-mysql-hardening

### ISSUE THREAD

**Issue by rndmh3ro** [dev-sec/ansible-mysql-hardening#36]
We'd like to support CentOS8!

Ideally we'd have testing for:

* kitchen with vagrant (https://github.com/dev-sec/ansible-mysql-hardening/blob/master/.kitchen.vagrant.yml)
* kitchen with docker (https://github.com/dev-sec/ansible-mysql-hardening/blob/master/.kitchen.yml)
* travis (https://github.com/dev-sec/ansible-mysql-hardening/blob/master/.travis.yml)

Docker-Image that should be used: https://cloud.docker.com/repository/docker/rndmh3ro/docker-centos8-ansible

**Comment by schurzi** [comment]
this is redundand now, will be solved by https://github.com/dev-sec/ansible-os-hardening/pull/291
