### ISSUE TITLE
New Tag?

### ISSUE THREAD

**Issue by deefour** [dev-sec/ansible-mysql-hardening#41]
Can you consider tagging this repo again? 2.0.0 is ~3 years old. I currently have to make a `requirements.yml` file pointing directly at this git repo to get an up to date role.

```yaml
- src: https://github.com/dev-sec/ansible-mysql-hardening
```

**Comment by rndmh3ro** [comment]
Done! :)

https://github.com/dev-sec/ansible-mysql-hardening/releases/tag/2.1.0
